### ISSUE TITLE
Exe file bug

### ISSUE THREAD

**Issue by DomZ560** [LilDrippyMyFnf/Fnf-EchoEngine#11]
The exe file won't load so yeah

**Comment by myffs** [comment]
We're currently working on fixing this bug,it should be fixed by 0.4.0

**Comment by DomZ560** [comment]
0.4 leak

**Comment by myffs** [comment]
fixed i think,idk the team really was dead so yeah

**Comment by ghost** [comment]
It's fixed already. Relax

**Comment by myffs** [comment]
yayayyyayayya
