### ISSUE TITLE
Please fix the uh copyKeys thing (its a new error so check the errors of the latest commit plz)

### ISSUE THREAD

**Issue by jmxamongusmodder** [LilDrippyMyFnf/Fnf-EchoEngine#29]
Please fix the uh copyKeys thing (its a new error so check the errors of the latest commit plz)

**Comment by MMbay64** [comment]
Explain it more

**Comment by jmxamongusmodder** [comment]
> Explain it more

so check the latest commit's error or the commit before
and you will see the issue
so i need someone to fix it

**Comment by jmxamongusmodder** [comment]
source/MainMenuState.hx:71: characters 15-34 : Map<String, Array<flixel.input.keyboard.FlxKey>> cannot be called
source/PlayState.hx:332: characters 20-3[9](https://github.com/LilDrippyMyFnf/Fnf-EchoEngine/actions/runs/3932835741/jobs/6725870351#step:6:10) : Map<String, Array<flixel.input.keyboard.FlxKey>> cannot be called
source/PlayState.hx:333: characters 24-43 : Map<String, Array<flixel.input.keyboard.FlxKey>> cannot be called
source/PlayState.hx:338: characters 4-23 : Map<String, Array<flixel.input.keyboard.FlxKey>> cannot be called
source/editors/EditorPlayState.hx:76: characters 4-23 : Map<String, Array<flixel.input.keyboard.FlxKey>> cannot be called

**Comment by MMbay64** [comment]
I don't really know how to fix that,I'm not the expert,just go to the discord server and discuss the issue

**Comment by jmxamongusmodder** [comment]
> I don't really know how to fix that,I'm not the expert,just go to the discord server and discuss the issue

invite is invalid and its from this uh project

**Comment by MMbay64** [comment]
Oh ok

**Comment by MMbay64** [comment]
Hold on a sec

**Comment by MMbay64** [comment]
https://discord.gg/bekYMvVu

Here
