### ISSUE TITLE
TODO: Fix compiling

### ISSUE THREAD

**Issue by MemeHoovy** [LilDrippyMyFnf/Fnf-EchoEngine#3]
![Screenshot 2022-12-24 022536](https://user-images.githubusercontent.com/97995998/209425831-0a7b00a3-cc8c-45bc-b70d-cb44c713b7b5.png)

**Comment by BambiGaming2022** [comment]
i think something is missing

**Comment by MemeHoovy** [comment]
> i think something is missing

you don't say

**Comment by LilDrippyMyFnf** [comment]
fixing it
