### ISSUE TITLE
Is their a lunix build by any chance?

### ISSUE THREAD

**Issue by OakShubs** [LilDrippyMyFnf/Fnf-EchoEngine#30]
I'm concern ed

**Comment by moxie-coder** [comment]
![ChrisHadfieldBadEnglishGIF](https://user-images.githubusercontent.com/124418090/220335380-ca2e93ee-9cb4-4840-b94b-d5721438fa24.gif)

and no there isn't yet

**Comment by myffs** [comment]
> ![ChrisHadfieldBadEnglishGIF](https://user-images.githubusercontent.com/124418090/220335380-ca2e93ee-9cb4-4840-b94b-d5721438fa24.gif) [ ![ChrisHadfieldBadEnglishGIF](https://user-images.githubusercontent.com/124418090/220335380-ca2e93ee-9cb4-4840-b94b-d5721438fa24.gif) ](https://user-images.githubusercontent.com/124418090/220335380-ca2e93ee-9cb4-4840-b94b-d5721438fa24.gif) [ ](https://user-images.githubusercontent.com/124418090/220335380-ca2e93ee-9cb4-4840-b94b-d5721438fa24.gif)
> 
> and no there isn't yet

the terrible image XDD
