### ISSUE TITLE
Ok how tf is animation editor NOT done?

### ISSUE THREAD

**Issue by JoseDev1664** [LilDrippyMyFnf/Fnf-EchoEngine#36]
![image](https://user-images.githubusercontent.com/129147438/229051523-dc2af372-d92b-49eb-9b37-5d942b7e4efa.png)
Its been at least a decade and its not done💀💀🙄🙄

**Comment by myffs** [comment]
Oh cuz my team is fucked up and like we don't even care about it at this point

And also, if your just gonna go around on my github repos posting dumpster shit, its best for you to fuck off and keep thoughts to yourslef, or just figure it out
