### ISSUE TITLE
The whole concept of cat mode sucks ass

### ISSUE THREAD

**Issue by JoseDev1664** [LilDrippyMyFnf/Fnf-EchoEngine#37]
Its not even a good idea, cuz how is the chart just gonna be automaticly put in the chart editor if the song has old chart

If you clear it, and u use cat mode, it'll just be blank in chart editor cuz the game will think ur playing normally

But if u use cat mode, any song u play, the chart will get messed up

**Comment by myffs** [comment]
that's your opinion. idc
