### ISSUE TITLE
no compile

### ISSUE THREAD

**Issue by min89xd** [LilDrippyMyFnf/Fnf-EchoEngine#4]
![image](https://user-images.githubusercontent.com/90361729/209448399-d03be487-3427-458f-a718-89668adfc0e4.png)

**Comment by myffs** [comment]
ummm

i'll try to fix it

**Comment by MemeHoovy** [comment]
@LilDrippyMyFnf I know what the issue is and I fixed it

**Comment by myffs** [comment]
> @LilDrippyMyFnf I know what the issue is and I fixed it

ok
