### ISSUE TITLE
Help with the exe file

### ISSUE THREAD

**Issue by myffs** [LilDrippyMyFnf/Fnf-EchoEngine#5]
can someone make a exe that like 'runs' the game

**Comment by MemeHoovy** [comment]
thought this was supposed to be an addon to psych? anyways you gotta compile the game to get that

**Comment by myffs** [comment]
> thought this was supposed to be an addon to psych? anyways you gotta compile the game to get that

it is,but we still need a exe file to compile all the stuff

**Comment by MemeHoovy** [comment]
> > thought this was supposed to be an addon to psych? anyways you gotta compile the game to get that
> 
> it is,but we still need a exe file to compile all the stuff

you compile it with lime build/test [OS]

**Comment by myffs** [comment]
ok
