### ISSUE TITLE
images in main menu not showing

### ISSUE THREAD

**Issue by myffs** [LilDrippyMyFnf/Fnf-EchoEngine#9]
flixel bug that needs repairment

**Comment by jmxamongusmodder** [comment]
> flixel bug that needs repairment

or your missing the files. i can check it on my own build. if i find the issue ill fix.

**Comment by myffs** [comment]
> > flixel bug that needs repairment
> 
> or your missing the files. i can check it on my own build. if i find the issue ill fix.

k
